### ISSUE TITLE
Organizer to-do list

### ISSUE THREAD

**Issue by ml-evs** [MADICES/MADICES-2022#1]
Some to-do's arising from today's meeting. If we end up with too many, we can spawn issues for each bulletpoint.

- [x] Follow-up with Caterina Barillari or someone else from OpenBIS
- [x] #2
- [ ] Agree on and assign broad breakout themes between organizers through issues/discussions
- [x] Begin contacting keynote speakers, panel discussions and other initiatives for shorter talks
    - [x] keynote preference #️1️⃣ contacted
- [X] CECAM registration page and advert 
- [ ] pre-workshop survey to inquiry background and interest of participants 
- [x] Add the workshop (+post-workshop) IM service, e.g. Discord
- [ ] Set up YouTube livestreaming for talks (letting CECAM handle the Zoom)
- [x] Choose license for the content in this repo
- [x] Confirm code of conduct for this repo/community/workshop
- [x] Finalize draft program
   -  [x] Publish draft program on CECAM page
- [ ] Choose service for writing the perspective paper: if GitHub, then separate repo?
- [ ] "Social" platform for workshop breaks, general discussion? We used Gather through CECAM in the past 
- [ ] Jointly prepare an opening talk that describes the workshop - will let us go into more detail than the advert
- [ ] Post-attendance survey
- [ ] Workshop CECAM report

**Comment by kjappelbaum** [comment]
Code of conduct looks good to me :D I guess we can check it of and if someone has a problem they can raise an issue ;)

**Comment by cthoyt** [comment]
not really sure where to put this but @StroemPhi would be a candidate to ask about panel discussions from his current interest in chemical information systems / ontologies via the German NFDI4chem project

**Comment by StroemPhi** [comment]
would be glad to participate :)

**Comment by ml-evs** [comment]
I would suggest we close this, most things here are now covered in the organization team discussions
